Repository acikkaynak/discord-it-yardim-bot, pull requests merged in 2023-02, with the labels that each got.

#14 refactor: Remove switch case duplicated codes to "sites"
  events/projects-button-handler.js
  package-lock.json
Labels: enhancement

#12 setup eslint config files and pre commit hook
  .eslintrc.js
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  .lintstagedrc
  .prettierrc
  package.json
Labels: enhancement

#18 Kayıt işlemi için kayıt komutu
  commands/kayit.js
Labels: enhancement

#30 Fikir komutu userid yerine etiketleme
  commands/fikir.js
Labels: enhancement

#31 "komutlar" typo fixed.
  commands/fikir.js
  commands/komutlar.js
Labels: enhancement

#29 Saat başı hatırlatma eklenmesi
  data/config.json
  events/ready.js
Labels: enhancement

#32 Development
  data/config.json
  events/ready.js
Labels: enhancement

#33 feat: github Discussions ve sosyal medya eklendi.
  commands/fikir.js
  data/config.json
  events/ready.js
Labels: enhancement

#41 BugFix: Kanal ID hatası giderildi.
  data/config.json
Labels: bug

#42 Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#44 Development Merge
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  commands/komutlar.js
  commands/pin.js
  data/config.json
  events/projects-button-handler.js
  events/ready.js
Labels: documentation, enhancement

#45 komutlar pin görünüm hatası giderildi.
  commands/komutlar.js
Labels: bug

#34 feat: adding translate command to bot
  commands/translate.js
  package.json
  yarn.lock
Labels: bug, help wanted

#55 Development Merge
  events/announcement-language-button.js
  events/ready.js
  yarn.lock
Labels: enhancement
